Add choice param for which buildmaster service or job to deploy
Khan/jenkins-jobs pull request #244
Opened 2024-10-28 20:59 UTC by jwbron

## Summary:
Adds a param to select which job should be deployed. Note, before merging, update the notify channel to 1s-and-0s
Issue: INFRA-10443

## Test plan:
Run as a replay in jenkins

2024-10-28 21:03 UTC, nathanjd approved these changes

2024-10-28 21:33 UTC, csilvers requested changes
Great, straigthforward enough!

You made a bunch of changes that were not strictly part of the PR at hand, such as adding the try/except.  I think they're all unnecessary at best.  Request Changes to revert them, and also to follow our function call style.  This is all stuff I mentioned in the last buildmaster review I did as well, which maybe you never saw?

2024-10-28 21:33 UTC, csilvers commented on jobs/deploy-buildmaster.groovy
> +).addChoiceParam(
```suggestion

).addChoiceParam(
```
(You need a blank line!)

2024-10-28 21:33 UTC, csilvers commented on jobs/deploy-buildmaster.groovy
> +          switch (serviceOrJob) {
```suggestion
          switch (params.SERVICE_OR_JOB) {
```

2024-10-28 21:33 UTC, csilvers commented on jobs/deploy-buildmaster.groovy
> +              error("Invalid service or job selected: ${serviceOrJob}")
```suggestion
              error("Invalid service or job selected: ${params.SERVICE_OR_JOB}")
```

2024-10-28 21:33 UTC, csilvers commented on jobs/deploy-buildmaster.groovy
> +              sh "make deploy"
```suggestion
              sh("make deploy");
```
and likewise for all the other sh's.

2024-10-28 21:33 UTC, csilvers commented on jobs/deploy-buildmaster.groovy
> +          echo "Deployment successful!"
```suggestion
          echo("Deployment successful!");
```

2024-10-28 21:33 UTC, csilvers commented on jobs/deploy-buildmaster.groovy
> +        }
Please get rid of this -- this behavior already happens automatically.

2024-10-28 22:15 UTC, csilvers approved these changes
awesome potato!

2024-10-29 23:21 UTC, csilvers commented on jobs/deploy-buildmaster.groovy
> +  notify([slack: [channel: '#1s-and-0s-deploys',
1s-and-0s-deploys, in practice, is really only useful for the deploy queue.  Everything else gets lost in the noise.  deploy-fastly.groovy sends to a #fastly channel for this reason.  I think that what you have here is fine, but another channel would probably be better.  Who owns buildmaster?  You could also just send it to #infrastructure, though that's kinda a dead channel too.

2024-10-29 23:33 UTC, csilvers commented on jobs/deploy-buildmaster.groovy
> +  notify([slack: [channel: '#1s-and-0s-deploys',
I think that would be fine!

There's also `#infrastructure-deploys`, that @MiguelCastillo set up, maybe that would be a good choice?  It mostly holds warnings now, but we could move this there.  And maybe fastly deploys one day too.

2024-10-30 00:12 UTC, merged