FEI-4674: Merge in 'master' when deploying ZNDs
Khan/jenkins-jobs pull request #58
Opened 2022-07-22 18:48 UTC by kevinbarabash

## Summary:
The regular deploy process merges 'master' into the deploy branch before deploying.  We want to do the same when deploying ZNDs.  This will avoid issues that can occur if a ZND is being deployed with out-of-date deploy scripts.

Issue: FEI-4674

Questions:
- Do we want to change GIT_REVISION to GIT_REVISIONS and allow people to deploy a ZND using multiple branches?

## Test plan:
- TBD (I'm not sure how to test this kind of change)

2022-07-22 20:50 UTC, csilvers requested changes
Overall this looks great!  I think putting mergeBranches into kaGit.groovy makes a lot of sense.

I think there are some syntax errors that will keep this from working though.  In any case we should test it.  The way you do this is to visit a page like https://jenkins.khanacademy.org/job/deploy/job/deploy-znd/5254/ and click on `replay` on the left pane.  Replace the contents of the "main script" window with your new deploy-znd.groovy code.  Replce the contents of the "kaGit" window with your new kaGit.groovy code.  Then click "run" and see how the job does.  Repeat until you get it all working.

2022-07-22 20:50 UTC, csilvers commented on jobs/deploy-znd.groovy
> +      // so that the ZND is deployed using out of date processes.  We call this
Do you mean "isn't deployed"?

2022-07-22 20:50 UTC, csilvers commented on vars/kaGit.groovy
> +   // the submodules on each branch, and being careful to clean at each step.
Now that you're in kaGit, this comment can probably just go away.

2022-07-22 20:50 UTC, csilvers commented on vars/kaGit.groovy
> +   kaGit.quickFetch("webapp");
I think this needs to be just `quickFetch` now?  I'm not 100% sure.

And likewise below.

2022-07-22 20:50 UTC, csilvers commented on vars/kaGit.groovy
> +// - tagName: string to tag the resulting commit with
You should probably document why this is necessary:
> tag the resulting commit with.  We need to tag the result of the merge so git doesn't prune it.

2022-07-22 20:50 UTC, csilvers commented on jobs/merge-branches.groovy
> -         def sha1 = mergeBranches();
You should delete the mergeBranches function now that you're not using it.

2022-07-22 21:48 UTC, csilvers approved these changes
Looks great!  I'm happy for you to land this once you've finished all the testing you want to do.

2022-07-25 14:14 UTC, kevinbarabash commented
Thanks for reviewing! 🙂

2022-07-25 14:14 UTC, merged